# Generated by Django 5.0.7 on 2024-07-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
    ]
